/*
LISTA DE CAMCIONES DE VIDEOS FAVORITOS DE YOUTUBE Y DECRI SI ES PILA O COLA. 
CREAR UN EJERCICIO: SIMULAR LOS TURNOS QUE SE PIDE EN UNA EPS PARA ACCEDER A UNA CITA MÉDICA Y DETERMINAR SI ES PILA O COLA.*/
